name: UnitTest

on:
  workflow_call:

env:
  PYTHON_VERSION: 3.11

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --only dev,test

      - run: poetry run pytest --cov-report term-missing --cov=src/test_central_templates tests/ -m "not onlylocal"

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: coverage.xml

      - uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.xml'
          badge: true
          format: 'markdown'
          output: 'both'
    
      - if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
  
      - run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
